version: "3.4"
services:
  app:
    image: php:alpine
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - "./:/app"
    working_dir: /app
    depends_on:
      - mongodb
      - mysql
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    build:
      context: docker/php
      dockerfile: dev.Dockerfile
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - "db-data:/var/lib/mysql/data"
  mongodb:
      container_name: mongodb
      image: mongo
      ports:
          - 27017:27017
      logging:
          driver: none
volumes:
  db-data: {}
